### ISSUE TITLE
Crash when trying to install a package using gittio as a module

### ISSUE THREAD

**Issue by AndreaVitale** [FokkeZB/gittio#118]
I'm trying to install a package using gittio as a commonjs module but the `install` method causes this error:

```
[ERROR] dk.napp.social:commonjs no distributable availableevelLifecycles Finishing
/usr/local/lib/node_modules/custom-cli/node_modules/gittio/lib/dist.js:29
      if (memo && available[scope] && available[scope][platform] && available[scope][platform][cmp.id]) {
                           ^

TypeError: Cannot read property 'undefined' of undefined
    at /usr/local/lib/node_modules/custom-cli/node_modules/gittio/lib/dist.js:29:28
    at Array.reduce (native)
    at Function._.reduce._.foldl._.inject (/usr/local/lib/node_modules/custom-cli/node_modules/gittio/node_modules/underscore/underscore.js:113:28)
    at Object.exports.isInstalled (/usr/local/lib/node_modules/custom-cli/node_modules/gittio/lib/dist.js:18:14)
    at /usr/local/lib/node_modules/custom-cli/node_modules/gittio/lib/gittio.js:322:26
    at Array.forEach (native)
    at Function._.each._.forEach (/usr/local/lib/node_modules/custom-cli/node_modules/gittio/node_modules/underscore/underscore.js:79:11)
    at component.lookup.action (/usr/local/lib/node_modules/custom-cli/node_modules/gittio/lib/gittio.js:320:7)
    at Request._callback (/usr/local/lib/node_modules/custom-cli/node_modules/gittio/lib/component.js:40:7)
    at Request.self.callback (/usr/local/lib/node_modules/custom-cli/node_modules/gittio/node_modules/request/request.js:186:22)
Andreas-MacBook-Pro:magneto Andrea$ 
```

**Comment by FokkeZB** [comment]
Who wrote this crap?! 😉

https://github.com/FokkeZB/gittio/blob/master/bin/gittio.js uses https://github.com/FokkeZB/gittio/blob/master/lib/gittio.js#L657-L660, which is what is exported as module API, but before it does, [it calls `config.init()`](https://github.com/FokkeZB/gittio/blob/master/bin/gittio.js#L174) which sets the `scope` that is `undefined` in your error. And after that it also sneaks in [`argsToParams()`](https://github.com/FokkeZB/gittio/blob/master/bin/gittio.js#L196) to further translate the input arg to params to pass to the method.

This needs some serious refactoring and separation of concerns:

- a new `index.js` should export a working module API, calling config and all.
- `bin/gittio.js` should use this API and only add the input to params thing.
- `lib/config.js` should not be state-full but return a config object to just use for the current call.
- Lots of clean up in all of this

I really wish I had time to do this, but I don't. Wanna help out? @dbankier maybe?

**Comment by dbankier** [comment]
@FokkeZB, sorry, neglecting my own projects atm. No time either.
