### ISSUE TITLE
CLI: Cannot read property 'current' of null

### ISSUE THREAD

**Issue by collinprice** [FokkeZB/gittio#95]
I keep getting the following error when I try to run any command.
```
➜  /tmp  gittio demo dk.napp.drawer -p ios

/usr/local/lib/node_modules/gittio/lib/config.js:140
    exports.current_modules = res.current;
                                 ^
TypeError: Cannot read property 'current' of null
    at /usr/local/lib/node_modules/gittio/lib/config.js:140:34
    at puts (/usr/local/lib/node_modules/gittio/node_modules/timodules/lib/timodules.js:37:7)
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

I can run it from the command line but all of the commands return the same error. Here is my version:
```
➜  /tmp  gittio -v
0.5.4
```

**Comment by collinprice** [comment]
Found the issue. The titanium command line tools are a dependancy.
```
npm install titanium -g
```

**Comment by FokkeZB** [comment]
Mmm, good one... not everyone has that anymore now with Appcelerator Platform 4.0 of course. I will see if I can use `appc ti` instead if `ti` is missing.

**Comment by sphairo** [comment]
gittio install -g

/usr/local/lib/node_modules/gittio/lib/config.js:140
    exports.current_modules = res.current;
                                 ^
TypeError: Cannot read property 'current' of null
    at /usr/local/lib/node_modules/gittio/lib/config.js:140:34
    at puts (/usr/local/lib/node_modules/gittio/node_modules/timodules/lib/timodules.js:37:7)
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

**Comment by sphairo** [comment]
this command is the solution npm install titanium -g after execute gittio install -g

**Comment by FokkeZB** [comment]
I have pushed a new version that will give a better error in the case you are missing the global Titanium CLI.
