### ISSUE TITLE
SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by kratosmat** [FokkeZB/gittio#96]
Hi all,
I am newbie about gittio and after installing it, I have tried to launch the following command:

-- gittio install -g facebook

and the result is:

[INFO]  facebook searching...

SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/usr/local/lib/node_modules/gittio/lib/component.js:27:22)
    at Request.self.callback (/usr/local/lib/node_modules/gittio/node_modules/request/request.js:123:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/gittio/node_modules/request/request.js:893:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/gittio/node_modules/request/request.js:844:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

Can someone help me on this trouble?

Thanks in advance,
Matteo.

**Comment by FokkeZB** [comment]
I think gitTio was down when you tried this. Can you try again?

I get:

```
≫ gittio install -g facebook
[INFO]  facebook searching...
[ERROR] facebook:commonjs no distributable available
[ERROR] facebook:mobileweb no distributable available
[ERROR] facebook:ios no distributable available
[ERROR] facebook:android no distributable available
```

Which is correct because there is no "facebook" component.
